SELECT
  fn_repo_ownership.github_team_id,
  fn_repo_ownership.github_team_name,
  fn_repo_ownership.github_team_slug,
  fn_repo_ownership.short_repo_name,
  fn_repo_ownership.full_repo_name,
  fn_repo_ownership.role_name,
  fn_repo_ownership.archived,
  fn_repo_ownership.galaxies_team,
  fn_repo_ownership.team_contact_email
FROM
  fn_repo_ownership() fn_repo_ownership(
    github_team_id,
    github_team_name,
    github_team_slug,
    short_repo_name,
    full_repo_name,
    role_name,
    archived,
    galaxies_team,
    team_contact_email
  );