SELECT
  fn_running_ec2_instances.account_name,
  fn_running_ec2_instances.app,
  fn_running_ec2_instances.stack,
  fn_running_ec2_instances.stage,
  fn_running_ec2_instances.image_id,
  fn_running_ec2_instances.instance_id,
  fn_running_ec2_instances.built_by_amigo,
  fn_running_ec2_instances.launch_time,
  fn_running_ec2_instances.type
FROM
  fn_running_ec2_instances() fn_running_ec2_instances(
    account_name,
    app,
    stack,
    stage,
    image_id,
    instance_id,
    built_by_amigo,
    launch_time,
    TYPE
  );