export const githubTables = [
	'github_issues',
	'github_languages',
	'github_organization_members',
	'github_organizations',
	'github_releases',
	'github_repositories',
	'github_repository_branches',
	'github_repository_collaborators',
	'github_repository_custom_properties',
	'github_repository_sboms',
	'github_team_members',
	'github_team_repositories',
	'github_teams',
	'github_workflows',
];
