#!/usr/bin/env bash
red="\033[0;31m"
clear="\033[0m"
yellow="\033[1;33m"
#check for staged changes in .env and ask user to confirm
if [[ $(git diff --cached --name-only | grep .env) ]]; then
  echo -e "${red}You have staged changes in the original .env file. This might include secrets you do not intend to commit."
  echo -e "${yellow}Are you sure you want to commit these changes?${clear} [y/N] "
  exec < /dev/tty
  read REPLY
  if [[ ! $REPLY =~ ^[Yy]$ ]]; then
    echo -e "${red}Aborting commit.${clear} Please discard unintended changes with `git restore .env` before committing again."
    exit 1
  fi
fi