flowchart
    DB[Cloudquery Database]
    snyk[Snyk Rest API]
    github[GitHub Rest API]
    cq[CloudQuery Batch Jobs]
    devxDev[Developer on the DevX team]
    dev[P&E developer]

    snyk --> |Data from snyk populates Cloudquery tables|cq
    github --> |Data from snyk populates Cloudquery tables|cq 
    aws --> |Data from snyk populates Cloudquery tables|cq
    %%"Data from snyk populates Cloudquery tables" "Cloudquery plugin running on fargate"
    cq --> |Cloudquery writes data to the DB|DB 
    %%"Cloudquery writes data to the DB"
    DB --> |1. Cloudquery data is used to calculate\n departmental compliance with obligations|repocop 
        %%" "SQL queries using Prisma ORM via TypeScript"
    repocop --> |2. Repocop stores compliance information\n about repos as a table in the cloudquery DB|DB
    DB --> |Cloudquery data powers grafana dashboards|grafana 
        %%"SQL queries on Postgres DB"
    repocop --> |Repocop raises PRs to fix issues, that are reviewed by developers|dev
    grafana --> |Compliance dashboards are used by DevX developers\n to track departmental progress towards obligations|devxDev
    grafana --> |Compliance dashboards are used by developers\n to track their team's progress towards obligations. \nThey also have read access to raw cloudquery tables.|dev
    repocop --> |Repocop sends notifications of events,\n or warnings to teams via Anghammarad|Anghammarad
    Anghammarad --> |Anghammarad delivers messages to developers\n about changes to their systems|dev