graph TB
  linkStyle default fill:#ffffff

  subgraph diagram ["Repocop - System Context"]
    style diagram fill:#ffffff,stroke:#ffffff

    1["<div style='font-weight: bold'>Developer</div><div style='font-size: 70%; margin-top: 0px'>[Person]</div><div style='font-size: 80%; margin-top:10px'>A Guardian software engineer</div>"]
    style 1 fill:#dddddd,stroke:#9a9a9a,color:#000000
    10["<div style='font-weight: bold'>Anghammarad</div><div style='font-size: 70%; margin-top: 0px'>[Software System]</div><div style='font-size: 80%; margin-top:10px'>A messaging service</div>"]
    style 10 fill:#dddddd,stroke:#9a9a9a,color:#000000
    4[("<div style='font-weight: bold'>Cloudquery DB</div><div style='font-size: 70%; margin-top: 0px'>[Software System]</div><div style='font-size: 80%; margin-top:10px'>Postgres database that stores<br />information from cloudquery<br />and Repocop</div>")]
    style 4 fill:#dddddd,stroke:#9a9a9a,color:#000000
    8["<div style='font-weight: bold'>Repocop</div><div style='font-size: 70%; margin-top: 0px'>[Software System]</div><div style='font-size: 80%; margin-top:10px'>A collection of lambdas that<br />track and enforce adherence<br />to best practices and<br />obligations. Includes<br />repocpo, interactive-monitor,<br />and snyk-integrator</div>"]
    style 8 fill:#dddddd,stroke:#9a9a9a,color:#000000

    4-. "<div>1. Cloudquery data is used to<br />calculate departmental<br />compliance with obligations</div><div style='font-size: 70%'>[SQL queries using Prisma ORM via TypeScript]</div>" .->8
    8-. "<div>2. Repocop stores compliance<br />information about repos as a<br />table in the cloudquery DB</div><div style='font-size: 70%'></div>" .->4
    8-. "<div>Repocop raises PRs to fix<br />issues, that are reviewed by<br />developers</div><div style='font-size: 70%'></div>" .->1
    8-. "<div>Repocop sends notifications<br />of events, or warnings to<br />teams via Anghammarad</div><div style='font-size: 70%'></div>" .->10
    10-. "<div>Anghammarad delivers messages<br />to developers about changes<br />to their systems</div><div style='font-size: 70%'>[Email or Google Chat]</div>" .->1
  end