kind: source
spec:
  name: github
  path: cloudquery/github
  version: v15.2.0
  tables:
    - github_copilot_seats
  skip_dependent_tables: true
  # turn on the backend options for incremental sync
  #backend_options:
  #  table_name: "cq_state_github"
  #  connection: "@@plugins.postgresql.connection"
  destinations:
    - postgresql
  spec:
    concurrency: 1000
    orgs:
      - guardian
    enterprises:
      - guardian
    app_auth:
      - org: guardian
        private_key_path: /private-key.pem
        app_id: ${file:/app-id}
        installation_id: ${file:/installation-id}
    include_archived_repos: true

---
kind: destination
spec:
  name: 'postgresql'
  path: 'cloudquery/postgresql'
  version: v${CQ_POSTGRES_DESTINATION}

  # Automatically apply migrations whenever plugins are updated.
  # Note: This is not encouraged if risk averse, so we should consider removing this once fully in production.
  # See: https://www.cloudquery.io/docs/advanced-topics/managing-versions#managing-plugin-versions
  migrate_mode: 'forced'

  # When `true`, each sync will add a row to the `cloudquery_sync_summaries` table.
  send_sync_summary: true
  spec:
    connection_string: ${DATABASE_URL}
