# Find full documentation here https://docs.github.com/en/actions/learn-github-actions/workflow-syntax-for-github-actions
name: Singleton image

permissions:
  contents: read

on:
  pull_request:
    paths:
      - 'containers/singleton/**'
  push:
    branches:
      - main
    paths:
      - 'containers/singleton/**'

  # Manual invocation.
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}/singleton

# Ensure we only ever have one build running at a time.
# If we push twice in quick succession, the first build will be stopped once the second starts.
# This avoids any race conditions.
concurrency:
  group: ${{ github.ref }}/singleton
  cancel-in-progress: true

jobs:
  build-and-push:
    uses: ./.github/workflows/release-image.yml
    with:
      IMAGE_NAME: singleton
    permissions:
      packages: write
