package com.gu.repocop

object MarkdownHelpers {

  def createPage(rules: List[Rule]): String = {
    val preamble: String =
      """
        |## Repo Rules
        |
        |This table is autogenerated from the Rules object as a human-readable reference to our GitHub best practices.
        |
        |""".stripMargin

    preamble + generateMarkdownTable(rules)
  }
  private def generateMarkdownTable(rules: List[Rule]): String = {
    val content = rules
      .map(repo => s"| ${repo.name} | ${repo.description} |")
      .mkString("\n")
    val header =
      "| Rule | Description |\n|---|---|\n"

    header + content
  }
}
